ENV:
DB_USERNAME:
DB_PASSWORD:
DB_NAME:
DB_PORT:
DB_HOSTNAME:
DB_MIGRATION_FILE:
DB_SEEDER_FILE:

EXTERNAL_IP:
HTTP_PORT:
DNS_PRINTER_IPV4_ADDRESS:
DNS_RETRIEVE_TRIGGER_URL:

GOOGLE_APPLICATION_SERVICE_ACCOUNT_EMAIL:
GOOGLE_APPLICATION_CREDENTIALS:
REACT_APP_GOOGLE_API_KEY:
GOOGLE_STORAGE_BUCKET_NAME:
GOOGLE_FORM_ID_ORDERS:
TWILIO_ACCOUNT_SID:
TWILIO_ACCOUNT_AUTH_TOKEN:
TWILIO_CONVERSATION_SERVICE_SID:
TWILIO_MESSAGING_SERVICE_SID:
