ENV: production
DB_USERNAME: postgres
DB_PASSWORD: eHon#X33S5P9XeLq
DB_NAME: thenolaconnect
DB_PORT: 5433
DB_HOSTNAME: 127.0.0.1

HTTP_PORT: 8080
DNS_PRINTER_IPV4_ADDRESS: 192.168.86.213
DNS_RETRIEVE_TRIGGER_URL: https://api.thenolaconnect.com/

GOOGLE_APPLICATION_SERVICE_ACCOUNT_EMAIL: web-dashboard@the-new-orleans-connection.iam.gserviceaccount.com
GOOGLE_APPLICATION_CREDENTIALS: /Users/devscrum/Code/thenolaconnect.com/pkg/the-new-orleans-connection-c42b40f02c07.json
REACT_APP_GOOGLE_API_KEY: AIzaSyANw5oWAUYpMvFpIXQ-aEd6AFQ3UqtjLt8
GOOGLE_STORAGE_BUCKET_NAME: the_new_orleans_connection_company_assets
GOOGLE_FORM_ID_ORDERS: 15ZkN8Kb_UB8JcXmwftywFlzDbkrGjqUQFM8Qi2hwVYM
TWILIO_ACCOUNT_SID: ACffbc5f2d34f8f7db7b6a0b0feb406dff
TWILIO_ACCOUNT_AUTH_TOKEN: e0501d6625eb97452e3620dce005327d
TWILIO_CONVERSATION_SERVICE_SID: IS1bf672d839574a1cada7f48146b20652
TWILIO_MESSAGING_SERVICE_SID: MG78e8fa43c614b800908c68b69479a860
